events {}

http {
    server_tokens off;

    server {
        listen 80;
        server_name recruitmentapp.duckdns.org recruitmentapi.duckdns.org;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name recruitmentapp.duckdns.org;

        ssl_certificate     /etc/letsencrypt/live/recruitmentapp.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/recruitmentapp.duckdns.org/privkey.pem;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 443 ssl;
        server_name recruitmentapi.duckdns.org;

        ssl_certificate     /etc/letsencrypt/live/recruitmentapi.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/recruitmentapi.duckdns.org/privkey.pem;

        location / {
            proxy_pass http://backend:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Cookie $http_cookie;
        }
    }
}
